// <auto-generated />
using System;
using FrontDesk.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FrontDesk.Db.Migrations
{
    [DbContext(typeof(FrontDeskDbc))]
    partial class FrontDeskDbcModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FrontDesk.Db.Tables.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Pin")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("pin");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("user_type");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.HasIndex("Pin")
                        .HasDatabaseName("ix_user_pin");

                    b.ToTable("user", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b2d8f9a4-1a3e-4e6f-8c02-000000000001"),
                            IsActive = true,
                            Name = "Office Worker",
                            Pin = "111111",
                            UserType = "Staff"
                        },
                        new
                        {
                            Id = new Guid("b2d8f9a4-1a3e-4e6f-8c02-000000000002"),
                            IsActive = true,
                            Name = "Warehouse Worker",
                            Pin = "222222",
                            UserType = "Staff"
                        },
                        new
                        {
                            Id = new Guid("b2d8f9a4-1a3e-4e6f-8c02-000000000003"),
                            IsActive = false,
                            Name = "Casual Worker",
                            Pin = "333333",
                            UserType = "Staff"
                        });
                });

            modelBuilder.Entity("FrontDesk.Db.Tables.Visit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Company")
                        .HasColumnType("text")
                        .HasColumnName("company");

                    b.Property<DateTime>("EntryAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("entry_at");

                    b.Property<DateTime?>("ExitAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("exit_at");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_visit");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_visit_user_id");

                    b.ToTable("visit", (string)null);
                });

            modelBuilder.Entity("FrontDesk.Db.Tables.Visit", b =>
                {
                    b.HasOne("FrontDesk.Db.Tables.User", "User")
                        .WithMany("Visits")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_visit_user_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FrontDesk.Db.Tables.User", b =>
                {
                    b.Navigation("Visits");
                });
#pragma warning restore 612, 618
        }
    }
}
